### ISSUE TITLE
Enforce IDs used for queries belong to the correct Entity

### ISSUE THREAD

**Issue by jerbaroo** [thma/generic-persistence#21]
Looking at the type signature for `selectById` we can see that the function takes a `Convertible id SqlValue => id`:
```hs
selectById :: forall a id. (Entity a, Convertible id SqlValue) => Conn -> id -> IO (Maybe a)
```
However this could be any `SqlValue`, it does not necessarily have to belong to the `Entity`.

***

There are various ways to structure that the the `id` belongs to the `Entity`:
```hs
selectById :: forall a id. Entity a id => Conn -> id -> IO (Maybe a)

class Entity a id | a -> id where
  idField :: String -- Already there.
  idValue :: id -> SqlValue -- Add this.
  ...
```

OR a solution that avoid adding a type parameter to `Entity`:

```hs
selectById :: forall a id. (Entity a, EntityId a id) => Conn -> id -> IO (Maybe a)

class EntityId a id | a -> id where
  idValue :: id -> SqlValue
```

**Comment by thma** [comment]
I see what you want to achieve.

But I'm not yet convinced of both approaches:
I like the first idea with the functional dependency `a -> id` better. as it more clearly connects a and id.

But I don't like the idea that the user has to define the mapping function `idValue :: id -> SqlValue`.
(In GP The mapping between all the fields and the database column-types is delegated to the Convert typeclass).

So maybe we could have something like :
```haskell
class Convertible id SqlValue => Entity a id | a -> id where
  idField :: String
  -- no need to define idValue as GP always uses `Convertible.convert` to do the mapping 
```

But I'm not sure if the compiler will accept that there is no function that uses the id type explicitely?

In the second solution with the Additional `EntityId` typeclass I don't like that the user has to instantiate a second typeclass where we again have this (In my eyes)  redundant definition of ìdValue`.

**Comment by thma** [comment]
seems the compiler does not object to my idea with . 
`class Convertible id SqlValue => Entity a id | a -> id`
I'll push a commit in a minute...

**Comment by thma** [comment]
Yes, being more typesafe is definitely a good thing, so I really appreciate your suggestion!

I only have one complaint about the solution:

It is no longer possible to instantiate the Entity type class in a `deriving` clause, as it is no longer a unary constraint. So one has always to derive an instance manually even if default methods are not overridden, like in `instance Entity Person Int`.

But apart from that minor issue it works great. I already had to fix several `selectById` calls in the test suite where I was not using the proper type for id fields.  So your idea helps to eliminate such errors!


I also like your idea of having a function `entityId :: a -> id` in the Entity type class like so:

```haskell
class Convertible id SqlValue => Entity a id | a -> id where
  ...
  entityId :: a -> id
  ...
```

To reduce effort on the user side I would like to have a default implementation for this. 
But I'm struggling to implement it with generics.

If we had such a function, we could implement `idValue :: a -> SqlValue` simply as:

```haskell
idValue :: a -> SqlValue
idValue = toSql . entityId
```

As I failed to come up with a genarics based solution I'm currently implementing ´idValue` in an awkward way:

I came up with something like this:
```haskell
idValue :: forall a id. (Entity id a) => Conn -> a -> IO SqlValue
idValue conn x = do
  sqlValues <- toRow conn x
  return (sqlValues !! idFieldIndex)
  where
    idFieldIndex = fieldIndex @a (idField @id @a)
```

If you have an idea how to implement `entityId :: a -> id` using generics that would be awesome!

**Comment by thma** [comment]
Hi again
I combined both your ideas, namely that an entity type has a functional dependency on the type of its primary key field AND on the fieldname of the pk field:

```haskell
class
  ( Generic a,
    HasConstructor (Rep a),
    HasSelectors (Rep a),
    Convertible SqlValue id,
    Convertible id SqlValue,
    HasField fieldName a id,
    Typeable fieldName
  )  =>
  Entity a fieldName id | a -> fieldName, a -> id where
```

now we have to declare an entity like so:

```haskell
data Person = Person { name :: String, age :: Int } deriving Generic

instance Entity Person "name" String
```

I just merged this into the main branch.

If you don't have further findings I would like to close the issue.
Thanks for your contribution !
